// Question - country(ies) with the most tourneys won
// Answer - Brazil

D01 Tourney Winners = 
    CALCULATE(
        VALUES ( A_tournaments[winner] ), 
        TOPN(1, 
             SUMMARIZE( A_tournaments, A_tournaments[winner], "wins", COUNTA( A_tournaments[tournament_id] ) ),
             [wins], DESC ))
